### ISSUE TITLE
URL datatype

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/inicheck#19]
* inicheck version: 0.3.3
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description
Could we add a URL datatype for accessing files hosted on the web?

The CriticalFilename and Filename are awesome datatypes, but I would like to be able to access netCDF files hosted on an OpenDAP server. This would require the path not be checked and not be treated as a relative path.

**Comment by micahjohnson150** [comment]
This came up today as @scotthavens was talking about the OpenDap implementation. It occurred to me that URL datatypes will be a little challenging due to colons being parsed super early in inicheck.

I think the current resolution might be to add quotes and protect anything in them. An issue with that is that if someone forgot it would be really challenging to warn them appropriately.

* inicheck version 0.3.5
